### ISSUE TITLE
How to extend the Parser

### ISSUE THREAD

**Issue by nadar** [deanblackborough/php-quill-renderer#102]
We do have some custom tags like mentions, it would be nice if i could register my own module, for example:

```php
class MentionModule extends .... BasicRendere
{
    public $attribute = 'mention';

    public function handle($input)
    {
        // do something with input and return changed value.
    }
}

$render->register(new MentionModule());
```

Maybe there is also already such an option to register a new not internal plugin to the rendered, but i could not find anything in the docs.

Here an example delta of such a mention plugin delta response (which is this plugin actually: https://github.com/afconsult/quill-mention):

```json
value="{
  "ops": [
    {
      "insert": "Hello "
    },
    {
      "insert": {
        "mention": {
          "id": "1",
          "value": "Fredrik Sundqvist",
          "denotationChar": "@"
        }
      }
    },
    {
      "insert": " \n"
    }
  ]
}"
```

As this is really the benefit of delta response, maybe it should be possible to register my own listener / renderer for a given tag.

Or at list a hook which i can attach to for EVERY element and decided by myself whether i want to change the value - or keep the basic renderer do his job.

**Comment by deanblackborough** [comment]
At the moment there is no way to register your own plugins but it is a fantastic idea.

The majority of the work is done in DBlackborough\Quill\Parser\Parser::parse(), it loops through the inserts and assigns a delta based on the attribute.

I'll add this to my todo list, in theory, it should be relatively simple to add support for registering plugins and extend DBlackborough\Quill\Parser\Parser::parse() to look at the registered plugins and then handle accordingly.

I can't promise this will be done within the next couple of days but it is now up at the top of my list.

I'm thinking something simple like 
```
$quill = new \DBlackborough\Quill\Render($quill_json);
$quill->registerPlugin(s)(string|array \Path\To\Class::class...); 
echo $quill->render();
```

**Comment by nadar** [comment]
In general, maybe it would be intresting to use the same mechanism (plugins) for existing parsing of deltas like bold, links, etc. then it would not be necessary to make switch() case for certain elements and everything works the same way, whether its a plugin or internal "basic" feature. But i assume it would take to much time to refactor.

**Comment by nadar** [comment]
I stared to work on my small own quill parsing library => https://github.com/nadar/quill-delta-to-html

The idea behind is that every attribute, block and element uses the same technique: https://github.com/nadar/quill-delta-to-html/tree/master/src/listener

Those elements can then handle the parsing and write to the output. This allows me the build the internal (out of the box element) the same way as the plugins (like mention plugin for quill). Maybe you like the idea for a next version of your library.

**Comment by nadar** [comment]
@deanblackborough after a few days of working with quill deltas, i really start to hate the delta output format 😄 just saying!

**Comment by deanblackborough** [comment]
Best of luck @nadar 

I agree, in general, the format is fine, issues start when you are looking at lists and new line use in general, why I sometimes split an insert.

I've been waylayed with other tasks but I'm going to start on the plugin system soon, potentially, moving everything to plugins makes a lot of sense although that is a more work.

Regarding your idea, yeah, I'm thinking of something very similar, lets people define how much they want to use, the issues arise with plain inserts and lists, a certain amount of logic needs to exist in the parser to know where lists start etc and how to handle a paragraph preceding or following a list etc, my split code handles most of this.

**Comment by nadar** [comment]
Finally i can say, almost all the tasks can be done now, including listening to plugins (like mention plugin): https://github.com/nadar/quill-delta-parser

If you like i can close this issue, but of course if you like to extend your library lets keep it open.

**Comment by deanblackborough** [comment]
Well done, I'll have a look when I am free, I'm leaving this open because I'm still going to add the feature, I do think it is a very good idea and version 4 will do everything via plugins.

A couple of your tests have @see links to my transmute-coffee website, you might want to change them to your demo site.

**Comment by nadar** [comment]
Thanks for pointing that out, i am not even sure what they where used for :-)
