### ISSUE TITLE
Link always gets parsed on new line

### ISSUE THREAD

**Issue by davidraijmakers** [deanblackborough/php-quill-renderer#108]
I am using the following versions:
"deanblackborough/php-quill-renderer": "^3.15",
"quill": "^1.3.6",

And i am trying to parse the following in the editor:
![screenshot 2018-12-10 at 11 58 44](https://user-images.githubusercontent.com/4717921/49728414-fb74b080-fc72-11e8-9d82-3813290ca291.png)

This has a link on the same line, on the second line a change of color in the text. The output of the quill javascript contents are the following:
![screenshot 2018-12-10 at 12 00 08](https://user-images.githubusercontent.com/4717921/49728472-29f28b80-fc73-11e8-8551-97630beb8c2e.png)

This shows that the 'contactformulier' link is added, but also the color change on the next line. I save this in the database but when i render it, it renders like this:
![screenshot 2018-12-10 at 12 02 09](https://user-images.githubusercontent.com/4717921/49728578-71791780-fc73-11e8-936f-451d2baa4c43.png)

The link is always on a new line. I am using the following code to render the deltas:

`$parser = new HtmlParser();
        $renderer = new HtmlRenderer();

        $parser->load($deltas)->parse();
        return $renderer->load($parser->deltas())->render();`

Is there something i am doing wrong? Or is this something that can be changed?

**Comment by deanblackborough** [comment]
@davidraijmakers That looks like a bug in the parser. I'll get this fixed as soon as possible, hopefully, this evening but if not definitely tomorrow evening.

Do you have the deltas you used to generate the HTML, that way I can add it to my test suite?

**Comment by davidraijmakers** [comment]
[deltas.txt](https://github.com/deanblackborough/php-quill-renderer/files/2663153/deltas.txt)
These are the delta's that i use

**Comment by deanblackborough** [comment]
David

Sorry, I've spent a little while looking at this and I can't seem to replicate the issue.

When I use the supplied deltas with v3.15 I get the below, I'm not getting the link on a new line, it is within the first paragraph

<--Generated by 3.15-->
&lt;p&gt;Wilt u &eacute;&eacute;n van bovenstaande punten wijzigen, dan &lt;a href=&quot;https://studiekeuze123.test/contact&quot; &gt;contactformulier&lt;/a&gt;.&nbsp; asd&lt;/p&gt;

&lt;p&gt;Wijzigingen die &lt;span style=&quot;color: #24372e;&quot;&gt;uiterlijk 20 november 2018 &lt;/span&gt;bij ons zijn binnengekomen, worden nog verwerkt in release 18.10 op 12 december 2018. Wijzigingen in CROHO (zoals nieuwe opleidingen) dienen ook uiterlijk 20 november door u te zijn ingevoerd om meegenomen te worden in de release van december 2018.&lt;/p&gt;
<--Generated by 3.15-->

Can you dump the HTML generated by my parser directly after the call to `$renderer->load($parser->deltas())->render();` and before you save to the database to see if it matches the above. 

It looks like you have something else parsing the content before generating the HTML. In your screenshot the link is `<a href="/contact">contactformulier</a>` yet if the supplied delta is used you should get `<a href="https://studiekeuze123.test/contact">contactformulier</a>`, the parser doesn't modify links, it wouldn't ever make the link relative.

I have a demo site at https://www.transmute-coffee.com/php-quill-renderer.php#demo - If you can replicate the issue there and send me the deltas or send through a script that shows the error I'd be more than happy to take a look but at the moment I can't really do anything.

**Comment by davidraijmakers** [comment]
I get the same one, it looks I removed some content before it that might have caused the problem. Here are the new deltas. There are links on 2 lines that are being shown in the editor on the same line. I'll add some pictures for you to understand it as well as it is Dutch.

![screenshot 2018-12-13 at 15 10 14](https://user-images.githubusercontent.com/4717921/49943839-397b0a00-fee9-11e8-919c-7734a186f6a4.png)
![screenshot 2018-12-13 at 15 10 04](https://user-images.githubusercontent.com/4717921/49943840-397b0a00-fee9-11e8-819d-1dd005833150.png)

[deltas.txt](https://github.com/deanblackborough/php-quill-renderer/files/2676328/deltas.txt)

**Comment by davidraijmakers** [comment]
P.S. I've tested it in the test link that you send me and this also is being shown wrong in the preview.

**Comment by davidraijmakers** [comment]
Do you maybe have time to look at this issue again?

**Comment by deanblackborough** [comment]
Hi David, thank you for the new deltas.

Which image is correct? I'm guessing the first one is what you entered into the Quill editor and the second is what was generated by my library?

I haven't the time to look at this today but will Tuesday evening, apologies for the delay getting back to you, been busy with other work.

**Comment by davidraijmakers** [comment]
The https://user-images.githubusercontent.com/4717921/49943840-397b0a00-fee9-11e8-819d-1dd005833150.png is the correct one (or how it should be shown).

But on https://user-images.githubusercontent.com/4717921/49943839-397b0a00-fee9-11e8-919c-7734a186f6a4.png you can see that:
 "Wilt u een van de bovenstaande"
<link to "bovenstaande"> is being shown on a new line where it shouldn't be.

Basically all the links at the bottom of the deltas are being shown on a new line where they shouldn't.

**Comment by deanblackborough** [comment]
David

I think I've managed to work out the problem. If there is a link in or close to a heading the parser gets confused, I have now got a couple of failing tests and am working on a fix, please keep an eye on this ticket for updates.

**Comment by davidraijmakers** [comment]
Can you give me an update or estimation when the update is going to be pushed?
I get that the christmas period isn't the time of the year to be pushing this code, but then i know when i can push this update.

**Comment by deanblackborough** [comment]
David

I'm working on it, there are updates in the `https://github.com/deanblackborough/php-quill-renderer/tree/v3.15.1` development branch.

At the moment there is one failing test which is stopping the release, links within a header don't render correctly, links at the end of a header render correctly.

I'm working on paid projects at the moment, this is a side project I work on when I have free time, I'll hopefully get to it soon but can't give you a specific date, it could be tomorrow, it could be next week.

You are welcome to try the branch listed above, it might work for you.

**Comment by davidraijmakers** [comment]
For security reasons we can't implement dev versions. I'll wait till the update has been pushed. Good luck!

**Comment by deanblackborough** [comment]
Resolved in v3.17.0 development branch, release soonish

**Comment by deanblackborough** [comment]
Closed. Resolved in v3.17.0, will be released shortly.
