### ISSUE TITLE
Video with attributes not supported

### ISSUE THREAD

**Issue by Humni** [deanblackborough/php-quill-renderer#127]
Awesome package my dude! There is a small bug in the parser.

Currently, a video with attributes breaks the parser and makes it fail quietly. This is due to the same issue as described in #86. Interestingly it doesn't throw an exception, it rather just "gives up" on the parsing as soon as it hits that point in the delta.

**Code to replicate**

```php
    $delta = '{"ops":[{"attributes":{"height":"315","width":"560"},"insert":{"video":"https://www.youtube.com/embed/qzgtJleG3r8"}}]}'
    $parser = new \DBlackborough\Quill\Parser\Html();
    $renderer = new \DBlackborough\Quill\Renderer\Html();
    $parser->load($delta)->parse();
    >> PHP Notice:  Undefined index: image in /vendor/deanblackborough/php-quill-renderer/src/Parser/Html.php on line 291
    $renderer->load($parser->deltas())->render();
    >> ""
```

**It doesn't affect videos without attributes, this is working as expected**

```php
    $delta = '{"ops":[{"insert":{"video":"https://www.youtube.com/embed/qzgtJleG3r8"}}]}'
    $parser = new \DBlackborough\Quill\Parser\Html();
    $renderer = new \DBlackborough\Quill\Renderer\Html();
    $parser->load($delta)->parse();
    $renderer->load($parser->deltas())->render();
    >> "<p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/qzgtJleG3r8"></iframe></p>\n"
```

I'm going to take a look into this and open a PR - unfortunately, a client found this one...

**Comment by deanblackborough** [comment]
@Humni 

Thank you for the PR and extra thanks for including the tests.
