### ISSUE TITLE
Uncaught Error: Class 'DBlackborough\Quill\Render' not found

### ISSUE THREAD

**Issue by lokit-iscitech** [deanblackborough/php-quill-renderer#134]
Copied the example in

https://www.transmute-coffee.com/php-quill-renderer.php#demo

and getting the error:

Uncaught Error: Class 'DBlackborough\Quill\Render' not found"
I copied the files in src directory in the same folder as the php file I am running. 

I am new to php and don't what is wrong.

**Comment by deanblackborough** [comment]
@lokit-iscitech 

It sounds like you are not using a dependancy manager like [Composer](https://getcomposer.org/).

Although in the same directory, your PHP script will not have access to any of the other classes, you will have to either include all the necessary classes [manually](https://www.php.net/manual/en/function.include.php) (not recommended) or switch to using Composer.

It is worth working out how to use Composer as you'll eventually want to use another library in your project.
