### ISSUE TITLE
All [P]aragraph blocks are merged into a single one

### ISSUE THREAD

**Issue by ciprian-cimpan** [deanblackborough/php-quill-renderer#40]
Hi Dean and thanks for this renderer!

I have a little issue on my end, though... While retrieving the content, all paragraphs are merged into a single one, and '\\n\\n' separators from the original json seem to be ignored. 

Any idea why this might happen?

Thanks!

**Comment by deanblackborough** [comment]
I'm due to do an update to my renderer very soon, this sounds like a bug, I will include a fix in the next release.

**Comment by deanblackborough** [comment]
Commit 43d42e4 to the v2.02.2 development branch may solve this issue, I fixed a bug where the parser is correctly adding the break index but wasn't adding the open and closing block tags, I'm going to add a couple of composite tests with more complex deltas before merging.

If you send me a delta that fails I could add that into the test suite.

**Comment by deanblackborough** [comment]
Added a new test, testMultipleParagraphsWithAttributes(), it fails, more work to do, will report back soon.

**Comment by deanblackborough** [comment]
This is still in progress, I had a few issues getting it to work for more complex deltas, after a few tries I've opted to rewrite the parser, finally making good progress. The original list code was a bit of a hack so this review was needed at some point.

I don't think it will take too long now, I think lists are sorted and I'm fairly happy with the newish paragraph code, I'll add simple attributes at the end when the paragraphs are done.

**Comment by deanblackborough** [comment]
Still an issue, will be fixed in v3.0

**Comment by deanblackborough** [comment]
Fixed in v3 alpha, will be released soon
