### ISSUE TITLE
Parser/Parse::load does not clear deltas

### ISSUE THREAD

**Issue by tominventisbe** [deanblackborough/php-quill-renderer#54]
When reusing the same parser to process multiple Quill JSONs, the new deltas are plainly stacked upon the previous ones, effectively merging any previous ones into the new one.

Thought I should report this as I just lost an hour trying to figure out why this happened, thinking I was invoking my own code multiple times :-).

EDIT: I'm using version 3, by the way.

**Comment by deanblackborough** [comment]
Cheers for the bug report

I will fix the issue this evening and push out a new version, apologies for not spotting it, I should have had a test that covered this.

**Comment by deanblackborough** [comment]
Resolved in #58 - StockTest::testMultipleInstancesInScript test added to confirm fix.
