### ISSUE TITLE
Error with specific JSON related to array where string is expected

### ISSUE THREAD

**Issue by tominventisbe** [deanblackborough/php-quill-renderer#55]
I'm receiving the following error for the JSON structure listed below.

`Internal message: Argument 1 passed to DBlackborough\Quill\Delta\Html\Compound::__construct() must be of the type string, array given, called in /var/www/app/vendor/deanblackborough/php-quill-renderer/src/Parser/Html.php on line 138`

I'm not always getting errors with this kind of structure, but with this JSON I seem to be able to reliably reproduce it.

```json
{
	"ops": [{
		"insert": "Text 1 "
	}, {
		"attributes": {
			"bold": true
		},
		"insert": "assumenda"
	}, {
		"insert": " Text 2.\n\n"
	}, {
		"attributes": {
			"width": "214",
			"style": "display: inline; float: right; margin: 0px 0px 1em 1em;"
		},
		"insert": {
			"image": "data:image/png;base64,ImageDataOmittedforSize"
		}
	}, {
		"insert": "\n\nText 3.\n\n"
	}]
}
```

Thanks!

**Comment by deanblackborough** [comment]
Fixed in #58 - This was down to the way I handle image deltas, the Compound delta doesn't know how to deal with images, added CompoundImage. The CompoundImage delta will add all passed in attributes as attributes on the `img`, that feature will be added to the Compound delta soon, issue #56
