### ISSUE TITLE
<sub>&<sup> support

### ISSUE THREAD

**Issue by ajaymeena** [deanblackborough/php-quill-renderer#8]
```
<sub></sub> and
<sup></sup>
```
attributes can be implemented similar to `<b></b>`

Check modified [code here...](https://www.dropbox.com/s/hrsyncsh3d30h5t/renderer.php?dl=0)

**Comment by deanblackborough** [comment]
@ajaymeena 

Thank you for raising the issue. I've added support for sub and sup in v0.40

I added support in a slightly different way because you appear to have modified an earlier version, you code is prior the creation of the HTML sub class.
